export const educationOptions = [
    "High School Diploma",
    "Associate's Degree",
    "Bachelor's Degree",
    "Master's Degree",
    "Doctoral Degree",
    "Vocational Training",
    "Professional Certification",
    "Online Courses",
    "Self-Taught",
    "Master's in Business",
    "Master's in Finance",
    "Master's in Marketing",
    "Master's in Engineering",
    "Master's in Computer Science",
    "Master's in Education",
    "Master's in Psychology",
    "Master's in Healthcare Administration",
    "Bachelor's in Business",
    "Bachelor's in Engineering",
    "Bachelor's in Computer Science",
    "Bachelor's in Nursing",
    "Bachelor's in Psychology",
    "Bachelor's in Biology",
    "Bachelor's in Environmental Science",
    "Bachelor's in Mechanical Engineering",
    "Bachelor's in Civil Engineering",
    "Bachelor's in Electrical Engineering",
    "Bachelor's in Chemical Engineering",
    "Others"
];