export const categoryList = [
    "Information Technology",
    "Software Development",
    "Data Science",
    "Web Development",
    "Mobile App Development",
    "Artificial Intelligence and Machine Learning",
    "Cybersecurity",
    "Digital Marketing",
    "Content Writing",
    "Graphic Design",
    "UX / UI Design",
    "Sales and Marketing",
    "Finance and Accounting",
    "Human Resources",
    "Customer Support",
    "Project Management",
    "Business Development",
    "Healthcare and Medicine",
    "Education and Teaching",
    "Engineering",
];